---
title: "BDA - Project"
authors: "Khang Nguyen, Son Le"
output:
  pdf_document:
    toc: yes
    toc_depth: 1
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# loading packages
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
library(brms)
library(bayesplot)
library("loo")
library(GGally)
library(rprojroot)
library(viridis)
root<-has_file("exploratory.rmd")$make_fix_file()
```

Data loading

```{r load_data}
airfoil <- read.csv("data/airfoil_self_noise.csv", sep=";")
colnames(airfoil) <- c("FR", "AOA", "CL", "FSV", "SSDT", "SSPL")
sample <- caTools::sample.split(airfoil, SplitRatio = 0.75)
train <- subset(airfoil, sample == TRUE)
test <- subset(airfoil, sample == FALSE)
print(airfoil[1:5,])
```

Exploratory data visualization

```{r pairs}
pairs <- ggpairs(airfoil)
pairs

gridExtra::grid.arrange(pairs[6,1], pairs[6,2], pairs[6,3],
                        pairs[6,4], pairs[6,5], pairs[6,6], nrow=2,
                        top="Pairs plot of response variable against all other variables")

ggparcoord(airfoil[sample(order(airfoil),500),],
           title = "Parallel coordinate plot",
           scale="center") +
  scale_color_viridis(discrete = T) +
  theme_minimal() +
  theme(
    legend.position="none",
    plot.title = element_text(size=20)
  )

reorder_cormat <- function(data) {
  cormat <- cor(data)
  # Use correlation between variables as distance
  dd <- as.dist((1-cormat)/2)
  hc <- hclust(dd)
  cormat <-cormat[hc$order, hc$order]
}

ggplot(data = reshape2::melt(reorder_cormat(airfoil)), aes(x=Var1, y=Var2, fill=value)) +
  geom_tile(color="white") +
  xlab("") + ylab("") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
    name="Pearson\nCorrelation") +
  theme_minimal()+
  labs(title="Correlation heatmap")
```