---
title: "BDA - Project"
authors: "Khang Nguyen, Son Le"
output:
  pdf_document:
    toc: yes
    toc_depth: 1
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# loading packages
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
library(bayesplot)
library("loo")
library(rprojroot)
root<-has_file("project.rmd")$make_fix_file()
```

Data loading

```{r}
data <- read.csv("data/airfoil_self_noise.csv", sep=";")
print(data[1:5,])
```

## Model 1)

```{r}
model_code_1 = root("models/model1.stan")
writeLines(readLines(model_code_1))
```

```{r}
dat <- list(n = length(data[[1]]),
            k = 5,
            X = subset(data, select=-scaled_sound_pressure_level),
            Y = data$scaled_sound_pressure_level
            )

fit_1 <- stan(file = model_code_1, data = dat, refresh = 0) 
```

Rhat check

```{r}
print(fit_1, pars = c("alpha","beta","sigma"))
```

Convergence visual check

```{r}
traceplot(fit_1, pars = c("alpha","beta","sigma"), inc_warmup = FALSE,  nrow = 4)
```

```{r}
stan_diag(fit_1)
```

Loo check

```{r}
log_lik_1 <- extract_log_lik(fit_1, merge_chains = FALSE)
r_eff_1 <- relative_eff(exp(log_lik_1)) 
loo_1 <- loo(log_lik_1, r_eff = r_eff_1)
print(loo_1$estimates)
pareto_k_table(loo_1)
```
In here, the effective number of parameters is 8

## Model 2)

The same code as Model 1 but with different priors

```{r}
model_code_2 = root("models/model2.stan")
writeLines(readLines(model_code_2))
```

```{r}
dat <- list(n = length(data[[1]]),
            k = 5,
            X = subset(data, select=-scaled_sound_pressure_level),
            Y = data$scaled_sound_pressure_level
            )

fit_2 <- stan(file = model_code_2, data = dat, refresh = 0) 
```

Rhat check

```{r}
print(fit_2, pars = c("alpha","beta","sigma"))
```

Convergence visual check

```{r}
traceplot(fit_2, pars = c("alpha","beta","sigma"), inc_warmup = FALSE,  nrow = 4)
```

```{r}
stan_diag(fit_2)
```

Loo check

```{r}
log_lik_2 <- extract_log_lik(fit_2, merge_chains = FALSE)
r_eff_2 <- relative_eff(exp(log_lik_2)) 
loo_2 <- loo(log_lik_2, r_eff = r_eff_2)
print(loo_2$estimates)
pareto_k_table(loo_2)
```

## Model comparision)

```{r}
comp <- loo_compare(loo_1, loo_2)
print(comp)
```